### ISSUE TITLE
Taking this down or shall I do it for you?

### ISSUE THREAD

**Issue by MistressPlague** [FoxxSVR/Xero#1]
: P

**Comment by FoxxSVR** [comment]
What

**Comment by FoxxSVR** [comment]
The thing is I dont want people taking it so I never referred it to vrc but also idk how you even found this without knowing who I am, none the less I'm creating more projects for future employment I'm going to be working on an sql project soon and then asp so I don't really care maybe this will help someone make their first client

**Comment by FoxxSVR** [comment]
Yeah that was my bad I didnt realize that I still had that in there, I used to use plague button api when the qm update dropped

**Comment by FoxxSVR** [comment]
I should also mention i didnt see the example button api because it never shown in my hierarchy not even the "Lagger" and "Lag" .cs files were showing so sorry for that too
