### ISSUE TITLE
I can still see my code. I'll just DMCA then.

### ISSUE THREAD

**Issue by MistressPlague** [FoxxSVR/Xero#2]
The buttonapi is still mine, the slider alone makes it obvious due to the watermarks I left.

**Comment by FoxxSVR** [comment]
What are you talking about this isn't your slider

**Comment by FoxxSVR** [comment]
Not only that but I never even use it to end with go fake claim someone else code thank you

**Comment by MistressPlague** [comment]
https://github.com/FoxxSVR/Xero/blob/main/Button%20Utils/Slider.cs#L105
https://github.com/PlagueVRC/PlagueButtonAPI/blob/new-ui/PlagueButtonAPI/PlagueButtonAPI/Controls/Slider.cs#L21

yes, it is stolen from me

**Comment by FoxxSVR** [comment]
Ah I see the confusion again some of my files don't get loaded into vs leaving the file to still be uploaded I was referring to the other slider that one is yours and like I said prior I used your button api a while ago (5 months ago maybe)

**Comment by MistressPlague** [comment]
So.. dmca it is?

**Comment by FoxxSVR** [comment]
Sure but you're gonna find nothing if you read you'd understand that I didn't use your code it was sitting in there as an unused hidden file. I deleted it because there was no reason to use it, it isn't used in my dll only in my project files
